spring:
  h2:
    console:
      path: /h2-console
  datasource:
    username: admin
    password:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor




#spring.datasource.url=jdbc:mysql://localhost:3306/task
#spring.datasource.username=root
#spring.datasource.password=admin
#spring.jpa.database-platform = org.hibernate.dialect.MySQL5Dialect
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto = update
#  spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#  spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
